name: MacOS-13 TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Date Stamp
        shell: bash
        id: date-stamp
        run: |
          echo "timestamp=$(date -u "+%Y%m%d%H%M_%S")" >> "$GITHUB_OUTPUT"

      - name: Setup build environment
        run: |
          # Install required tools for macOS build
          brew install autoconf automake libtool ccache lz4 libsodium openssl@3 zlib libmicrohttpd ninja pkg-config texinfo llvm@16
          mkdir -p ~/.ccache

      # Improved cache with better restore keys
      - name: Restore ccache
        uses: actions/cache/restore@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-macos-13-portable-ccache-${{ steps.date-stamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-macos-13-portable-ccache-
            ${{ runner.os }}-${{ runner.arch }}-portable-ccache-

      - name: Build TON
        run: |
          git submodule sync --recursive
          git submodule update
          cp assembly/native/build-macos-portable.sh .
          chmod +x build-macos-portable.sh
          ./build-macos-portable.sh -t -a -c -o 13.0
          ccache -sp

      - name: Save ccache
        uses: actions/cache/save@v4
        if: always()  # Save cache even if build fails
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-macos-13-portable-ccache-${{ steps.date-stamp.outputs.timestamp }}

      # Run tests in parallel with reduced timeout for faster feedback
      - name: Run Tests
        run: |
          cd build        
          ctest --output-on-failure --timeout 900 --parallel $(sysctl -n hw.ncpu)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ton-x86_64-macos
          path: artifacts
